### ISSUE TITLE
Documentation for Version 2 no longer available

### ISSUE THREAD

**Issue by ganar** [jenius/roots.cx#35]
Kudos to the development team for Roots V3. We understand the excitement over the new version, and would appreciate access to the documentation of version 2, which is no longer reachable, in order to work on the development of a project we are currently building on that version

**Comment by jenius** [comment]
Hey @ganar -- yup, I'm sorry I'll have a backup online this week for v2.

**Comment by ganar** [comment]
Yo can use something like the URL scheme in bootstrap `getbootstrap/2.4/` and duplicate the entire site for version 2 within that address

**Comment by jenius** [comment]
Hey @ganar, sorry for the delay. This iteration of the docs are now available at http://v1.roots.cx/

**Comment by ganar** [comment]
Thanks a lot @jenius !
